# =============================================
# Konfigurasi Aplikasi Reservasi Hotel
# Spring Boot + MySQL + Thymeleaf
# Dimas Mulyo - Tugas Pemrograman 2
# =============================================

# Nama Aplikasi
spring.application.name=Hotel Reservasi

# Konfigurasi MySQL (JDBC)
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_reservasi_dimas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Jakarta
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Konfigurasi Thymeleaf
spring.thymeleaf.cache=false

# Port Server
server.port=8082
